name: Build
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - '**/*.swift'
  push:
    branches:
      - 'main'
    paths:
      - '**/*.swift'

permissions:
  contents: read
  issues: read
  checks: write

jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          submodules: recursive
      - name: Test
        run: |
          xcodebuild test \
            -scheme "piper-objc-Package" \
            -destination "platform=macOS" \
            -only-testing:"piper-objc-tests"
      - name: Build
        run: |
          swift build -c release
