name: Build
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

permissions:
  contents: read
  issues: read
  checks: write

jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          submodules: recursive
      - name: Test
        run: |
          swift test -Xcc -DPATH_ESPEAK_DATA="\"\""
      - name: Build
        run: |
          swift build -c release
